require("../../WebModule/lib/Reflection.js");
require("../../WebModule/lib/Console.js");
require("../../WebModule/lib/Valid.js");
require("../../WebModule/lib/Help.js");
require("../../WebModule/lib/Task.js");
require("../../WebModule/lib/Test.js");
require("../lib/WMAdler32.js");
require("../release/WMAdler32.min.js");
require("./testcase.js");
